


import UiApp from '@/components/ui/ui'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Akbar Mohammadi',
  description: ' Front end Developer ',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      
      <body className={` ${inter.className} cont container mx-auto flex flex-wrap max-sm:inline-block min-h-screen justify-center `}>
           <UiApp/>
        {children}
          
        </body>
    </html>
  )
}


/* import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
} */
